/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KrouselRouteImport } from './routes/krousel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetsPtbRouteImport } from './routes/projets.ptb'
import { Route as ProjetsFestiSafeRouteImport } from './routes/projets.festi-safe'
import { Route as ProjetsShowshanksRouteImport } from './routes/projets.showshanks'

const KrouselRoute = KrouselRouteImport.update({
  id: '/krousel',
  path: '/krousel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsPtbRoute = ProjetsPtbRouteImport.update({
  id: '/projets/ptb',
  path: '/projets/ptb',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsFestiSafeRoute = ProjetsFestiSafeRouteImport.update({
  id: '/projets/festi-safe',
  path: '/projets/festi-safe',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsShowshanksRoute = ProjetsShowshanksRouteImport.update({
  id: '/projets/showshanks',
  path: '/projets/showshanks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/krousel': typeof KrouselRoute
  '/projets/ptb': typeof ProjetsPtbRoute
  '/projets/festi-safe': typeof ProjetsFestiSafeRoute
  '/projets/showshanks': typeof ProjetsShowshanksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/krousel': typeof KrouselRoute
  '/projets/ptb': typeof ProjetsPtbRoute
  '/projets/festi-safe': typeof ProjetsFestiSafeRoute
  '/projets/showshanks': typeof ProjetsShowshanksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/krousel': typeof KrouselRoute
  '/projets/ptb': typeof ProjetsPtbRoute
  '/projets/festi-safe': typeof ProjetsFestiSafeRoute
  '/projets/showshanks': typeof ProjetsShowshanksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/krousel' | '/projets/ptb' | '/projets/festi-safe' | '/projets/showshanks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/krousel' | '/projets/ptb' | '/projets/festi-safe' | '/projets/showshanks'
  id: '__root__' | '/' | '/krousel' | '/projets/ptb' | '/projets/festi-safe' | '/projets/showshanks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KrouselRoute: typeof KrouselRoute
  ProjetsPtbRoute: typeof ProjetsPtbRoute
  ProjetsFestiSafeRoute: typeof ProjetsFestiSafeRoute
  ProjetsShowshanksRoute: typeof ProjetsShowshanksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/krousel': {
      id: '/krousel'
      path: '/krousel'
      fullPath: '/krousel'
      preLoaderRoute: typeof KrouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/ptb': {
      id: '/projets/ptb'
      path: '/projets/ptb'
      fullPath: '/projets/ptb'
      preLoaderRoute: typeof ProjetsPtbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/festi-safe': {
      id: '/projets/festi-safe'
      path: '/projets/festi-safe'
      fullPath: '/projets/festi-safe'
      preLoaderRoute: typeof ProjetsFestiSafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/showshanks': {
      id: '/projets/showshanks'
      path: '/projets/showshanks'
      fullPath: '/projets/showshanks'
      preLoaderRoute: typeof ProjetsShowshanksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KrouselRoute: KrouselRoute,
  ProjetsPtbRoute: ProjetsPtbRoute,
  ProjetsFestiSafeRoute: ProjetsFestiSafeRoute,
  ProjetsShowshanksRoute: ProjetsShowshanksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
