/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KrouselRouteImport } from './routes/krousel'
import { Route as IndexRouteImport } from './routes/index'

const KrouselRoute = KrouselRouteImport.update({
  id: '/krousel',
  path: '/krousel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/krousel': typeof KrouselRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/krousel': typeof KrouselRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/krousel': typeof KrouselRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/krousel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/krousel'
  id: '__root__' | '/' | '/krousel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KrouselRoute: typeof KrouselRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/krousel': {
      id: '/krousel'
      path: '/krousel'
      fullPath: '/krousel'
      preLoaderRoute: typeof KrouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KrouselRoute: KrouselRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
