/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KrouselRouteImport } from './routes/krousel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetsPtbRouteImport } from './routes/projets.ptb'

const KrouselRoute = KrouselRouteImport.update({
  id: '/krousel',
  path: '/krousel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsPtbRoute = ProjetsPtbRouteImport.update({
  id: '/projets/ptb',
  path: '/projets/ptb',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/krousel': typeof KrouselRoute
  '/projets/ptb': typeof ProjetsPtbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/krousel': typeof KrouselRoute
  '/projets/ptb': typeof ProjetsPtbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/krousel': typeof KrouselRoute
  '/projets/ptb': typeof ProjetsPtbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/krousel' | '/projets/ptb'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/krousel' | '/projets/ptb'
  id: '__root__' | '/' | '/krousel' | '/projets/ptb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KrouselRoute: typeof KrouselRoute
  ProjetsPtbRoute: typeof ProjetsPtbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/krousel': {
      id: '/krousel'
      path: '/krousel'
      fullPath: '/krousel'
      preLoaderRoute: typeof KrouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/ptb': {
      id: '/projets/ptb'
      path: '/projets/ptb'
      fullPath: '/projets/ptb'
      preLoaderRoute: typeof ProjetsPtbRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KrouselRoute: KrouselRoute,
  ProjetsPtbRoute: ProjetsPtbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
